allowBuilds:
  '@google/genai': false
  msw: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - '@google/genai'
  - msw
  - protobufjs
  - sharp
  - unrs-resolver
